# Generated by Django 3.1.3 on 2020-12-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('economy', 'Ekonomi'), ('art', 'Sanat'), ('sport', 'Spor'), ('technolgy', 'Teknoloji')], max_length=50)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
